services:
  - type: web
    name: dutch-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python dutch_bot.py"
    envVars:
      - key: BOT_TOKEN
        value: 7884882687:AAFLo5kG1WXuGPcX44glo0cMCFuwJgq8YL0
      - key: ADMIN_ID
        value: "408823124"
      - key: WEBHOOK_URL
        value: "https://ailingo-oag0.onrender.com/webhook/7884882687:AAFLo5kG1WXuGPcX44glo0cMCFuwJgq8YL0"