services:
  - type: worker
    name: ailingo-bot
    runtime: python
    repo: https://github.com/ailingobot/ailingo.git
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python dutch_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DB_PATH
        value: /mnt/data/bot.db
    plan: free
    autoDeploy: true
